name: CI-CD WordPress

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.32.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose

      - name: Generate Kubernetes manifests with Kompose
        run: |
          rm -rf kube_temp
          mkdir kube_temp
          kompose convert -f docker-compose.yml -o kube_temp/

      - name: Add Kubernetes Secret
        run: |
          cp kube_temp/wordpress-secret.yaml kube_temp/wordpress-secret.yaml || true

      - name: Zip Kubernetes manifests
        run: |
          zip -r KayelahoutouZabdielWordpress.zip kube_temp

      - name: Upload ZIP to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: RenduDevopsKube/
          local-dir: KayelahoutouZabdielWordpress.zip
          dangerous-clean-slate: false
          state-name: "none"

