name: CI/CD WordPress

# Déclencheur : push ou pull request sur main
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.38.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/kompose
      - name: Generate Kubernetes manifests with Kompose
        run: |
          rm -rf kube_temp
          mkdir kube_temp
          kompose convert -o kube_temp/
      - name: Préparer dossier pour FTP
        run: |
          mkdir ftp_upload
          cp -r kube_temp ftp_upload/
          zip -r KayelahoutouZabdielWordpress.zip ftp_upload/*
      - name: Upload ZIP to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: RenduDevopsKube/
          local-dir: ./ftp_upload/
          dangerous-clean-slate: false
          state-name: "none"
